CREATE TABLE tb_ai_log_error_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    analysis_task_id BIGINT NOT NULL,
    file_record_id BIGINT,
    issue_group_id BIGINT,
    environment VARCHAR(32) NOT NULL,
    system_code VARCHAR(64) NOT NULL,
    module_code VARCHAR(128) NOT NULL,
    log_date DATE NOT NULL,
    aggregate_type VARCHAR(16) NOT NULL,
    aggregate_key CHAR(64) NOT NULL,
    occurrence_count BIGINT DEFAULT 1,
    first_seen_time TIMESTAMP,
    last_seen_time TIMESTAMP,
    root_cause_category VARCHAR(32) NOT NULL,
    matched_rule_id BIGINT,
    expected BOOLEAN DEFAULT FALSE,
    ai_required BOOLEAN DEFAULT TRUE,
    reason_code VARCHAR(128),
    log_time TIMESTAMP,
    start_line BIGINT NOT NULL,
    end_line BIGINT NOT NULL,
    start_byte BIGINT NOT NULL,
    end_byte BIGINT NOT NULL,
    location_mode VARCHAR(32) NOT NULL,
    truncated BOOLEAN DEFAULT FALSE,
    match_type VARCHAR(32) NOT NULL,
    thread_name VARCHAR(512),
    trace_id VARCHAR(256),
    tid VARCHAR(256),
    request_id VARCHAR(256),
    logger_class VARCHAR(512),
    logger_method VARCHAR(256),
    logger_line INT,
    exception_class VARCHAR(512),
    exception_message TEXT,
    root_cause_exception VARCHAR(512),
    root_cause_message TEXT,
    business_class VARCHAR(512),
    business_method VARCHAR(256),
    business_line INT,
    trigger_channel VARCHAR(32) NOT NULL,
    normalized_message TEXT,
    simplified_stack TEXT,
    strict_fingerprint CHAR(64) NOT NULL,
    stable_fingerprint CHAR(64) NOT NULL,
    fingerprint_version VARCHAR(32) NOT NULL,
    sample_content TEXT,
    sample_content_truncated BOOLEAN DEFAULT FALSE,
    sample_quality_score SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (analysis_task_id, aggregate_type, aggregate_key)
);
