-- badfisher-ai-log: Flyway V1, empty database only; no business seed data.


CREATE TABLE IF NOT EXISTS `tb_ai_log_module_config` (
    `id`                     BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `environment`            VARCHAR(32) NOT NULL COMMENT '环境编码',
    `system_code`            VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`            VARCHAR(128) NOT NULL COMMENT '模块编码',
    `enabled`                TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    `server_host`            VARCHAR(128) NOT NULL COMMENT '日志服务器IP或域名',
    `server_port`            INT NOT NULL DEFAULT 22 COMMENT 'SSH端口',
    `ssh_username`           VARCHAR(64) NOT NULL COMMENT 'SSH只读用户',
    `credential_ref`         VARCHAR(128) DEFAULT NULL COMMENT 'SSH凭证引用',
    `remote_directory`       VARCHAR(512) NOT NULL COMMENT '远程日志目录',
    `log_file_prefix`        VARCHAR(128) NOT NULL COMMENT '日志文件前缀',
    `sync_error_log`         TINYINT(1) NOT NULL DEFAULT 1 COMMENT '同步err日志',
    `sync_all_log`           TINYINT(1) NOT NULL DEFAULT 1 COMMENT '同步all日志',
    `local_sub_directory`    VARCHAR(128) DEFAULT NULL COMMENT '本地模块单级目录别名，为空时使用module_code',
    `parser_profile`         VARCHAR(64) NOT NULL DEFAULT 'JAVA' COMMENT '解析配置',
    `analysis_module`        VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '分析模块',
    `code_sync_enabled`      TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否在AI分析前同步Git源码：1是，0否',
    `git_repository_url`     VARCHAR(1024) DEFAULT NULL COMMENT 'Git仓库地址，不包含凭证',
    `git_branch`             VARCHAR(128) DEFAULT NULL COMMENT 'Git目标分支',
    `sync_priority`          INT NOT NULL DEFAULT 100 COMMENT '同步优先级，小值优先',
    `remark`                 VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_user_id`         INT NOT NULL DEFAULT 0 COMMENT '创建用户ID，初始化数据为0',
    `create_user_name`       VARCHAR(128) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建用户名',
    `create_time`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user_id`         INT NOT NULL DEFAULT 0 COMMENT '更新用户ID，初始化数据为0',
    `update_user_name`       VARCHAR(128) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新用户名',
    `update_time`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `lock_version`           INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_env_system_module` (`environment`, `system_code`, `module_code`),
    KEY `idx_enabled_priority` (`enabled`, `sync_priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志分析生产模块动态配置';



CREATE TABLE IF NOT EXISTS `tb_ai_log_sync_task` (
    `id`                      BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_no`                 VARCHAR(64) NOT NULL COMMENT '同步任务号',
    `system_code`             VARCHAR(64) NOT NULL COMMENT '系统编码',
    `environment`             VARCHAR(32) NOT NULL COMMENT '环境编码',
    `log_date`                DATE NOT NULL COMMENT '日志日期',
    `trigger_type`            VARCHAR(32) NOT NULL COMMENT '触发来源',
    `status`                  VARCHAR(32) NOT NULL COMMENT '任务状态：PENDING、RUNNING、SUCCESS、PARTIAL_SUCCESS、FAILED、CONFLICT',
    `total_module_count`      INT NOT NULL DEFAULT 0 COMMENT '模块总数',
    `success_module_count`    INT NOT NULL DEFAULT 0 COMMENT '同步成功模块数',
    `failed_module_count`     INT NOT NULL DEFAULT 0 COMMENT '同步失败模块数',
    `start_time`              DATETIME DEFAULT NULL COMMENT '任务开始时间',
    `finish_time`             DATETIME DEFAULT NULL COMMENT '任务完成时间',
    `heartbeat_time`          DATETIME DEFAULT NULL COMMENT '执行心跳时间',
    `error_message`           VARCHAR(2000) DEFAULT NULL COMMENT '最后一次失败原因',
    `create_time`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_no` (`task_no`),
    UNIQUE KEY `uk_sync_scope` (`environment`, `system_code`, `log_date`),
    KEY `idx_sync_task_scope` (`environment`, `system_code`, `log_date`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志系统级同步任务';


CREATE TABLE IF NOT EXISTS `tb_ai_log_sync_module_task` (
    `id`                    BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `sync_task_id`          BIGINT NOT NULL COMMENT '系统同步任务ID',
    `module_config_id`      BIGINT NOT NULL COMMENT '模块配置ID',
    `module_code`           VARCHAR(128) NOT NULL COMMENT '模块编码',
    `status`                VARCHAR(32) NOT NULL COMMENT '模块任务状态：PENDING、RUNNING、SUCCESS、FAILED、CONFLICT',
    `total_file_count`      INT NOT NULL DEFAULT 0 COMMENT '待同步文件总数',
    `success_file_count`    INT NOT NULL DEFAULT 0 COMMENT '同步成功文件数',
    `failed_file_count`     INT NOT NULL DEFAULT 0 COMMENT '同步失败文件数',
    `start_time`            DATETIME DEFAULT NULL COMMENT '模块任务开始时间',
    `finish_time`           DATETIME DEFAULT NULL COMMENT '模块任务完成时间',
    `error_message`         VARCHAR(2000) DEFAULT NULL COMMENT '最后一次失败原因',
    `create_time`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sync_task_module` (`sync_task_id`, `module_code`),
    KEY `idx_module_task_status` (`status`),
    KEY `idx_module_config` (`module_config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志模块级同步任务';


CREATE TABLE IF NOT EXISTS `tb_ai_log_file_record` (
    `id`                     BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `system_code`            VARCHAR(64) NOT NULL COMMENT '系统编码',
    `environment`            VARCHAR(32) NOT NULL COMMENT '环境编码',
    `module_code`            VARCHAR(128) NOT NULL COMMENT '模块编码',
    `log_date`               DATE NOT NULL COMMENT '日志所属日期',
    `file_type`              VARCHAR(32) NOT NULL COMMENT '文件类型：APPLICATION、ERROR',
    `remote_path`            VARCHAR(1024) NOT NULL COMMENT '远程日志完整路径',
    `local_path`             VARCHAR(1024) NOT NULL COMMENT '本地ready文件完整路径',
    `file_name`              VARCHAR(512) NOT NULL COMMENT '日志文件名',
    `file_size`              BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小，单位字节',
    `sync_task_id`           BIGINT NOT NULL COMMENT '系统级同步任务ID',
    `sync_module_task_id`    BIGINT NOT NULL COMMENT '模块级同步任务ID',
    `sync_status`            VARCHAR(32) NOT NULL COMMENT '同步状态：PENDING、SYNCING、READY、FAILED',
    `parse_status`           VARCHAR(32) NOT NULL COMMENT '解析状态：WAITING、PARSING、PARSED、FAILED',
    `ready_time`             DATETIME DEFAULT NULL COMMENT '文件发布到ready目录的时间',
    `parse_time`             DATETIME DEFAULT NULL COMMENT '最近一次解析完成时间',
    `error_message`          VARCHAR(2000) DEFAULT NULL COMMENT '同步或解析的最后一次失败原因',
    `create_time`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_module_task_file_type` (`sync_module_task_id`, `file_type`),
    KEY `idx_file_pre_analysis` (`log_date`, `sync_status`, `parse_status`),
    KEY `idx_file_scope` (`environment`, `system_code`, `module_code`, `log_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志文件同步与解析生命周期记录';



CREATE TABLE IF NOT EXISTS `tb_ai_log_analysis_task` (
    `id`                       BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_no`                  VARCHAR(64) NOT NULL COMMENT '全局唯一分析任务号',
    `file_record_id`           BIGINT NULL COMMENT '待分析文件记录ID；本地直读模式为空',
    `sync_task_id`             BIGINT NULL COMMENT '来源系统级同步任务ID；本地直读模式为空',
    `sync_module_task_id`      BIGINT NULL COMMENT '来源模块级同步任务ID；本地直读模式为空',
    `environment`              VARCHAR(32) NOT NULL COMMENT '环境编码',
    `system_code`              VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`              VARCHAR(128) NOT NULL COMMENT '模块编码',
    `log_date`                 DATE NOT NULL COMMENT '日志所属日期',
    `status`                   VARCHAR(32) NOT NULL COMMENT '分析状态：WAITING、PARSING、SUCCESS、FAILED',
    `fingerprint_version`      VARCHAR(32) NOT NULL COMMENT '指纹算法版本',
    `raw_event_count`          BIGINT NOT NULL DEFAULT 0 COMMENT '原始事件数；0=尚未统计到事件',
    `strict_error_count`       BIGINT NOT NULL DEFAULT 0 COMMENT '标准Header严格识别ERROR数',
    `fallback_error_count`     BIGINT NOT NULL DEFAULT 0 COMMENT '受控回退ERROR数',
    `rejected_event_count`     BIGINT NOT NULL DEFAULT 0 COMMENT '明确非ERROR而拒绝的事件数',
    `suppressed_error_count`    BIGINT NOT NULL DEFAULT 0 COMMENT '命中过滤规则而未生成Event的ERROR数',
    `discarded_unknown_count`   BIGINT NOT NULL DEFAULT 0 COMMENT '无有效异常身份而丢弃的ERROR数',
    `persisted_error_count`    BIGINT NOT NULL DEFAULT 0 COMMENT '最终Event对应的ERROR次数',
    `issue_count`              BIGINT NOT NULL DEFAULT 0 COMMENT '命中的稳定Issue数',
    `retry_count`              INT NOT NULL DEFAULT 0 COMMENT '分析重试次数；0=首次执行未重试',
    `start_time`               DATETIME DEFAULT NULL COMMENT '分析开始时间',
    `finish_time`              DATETIME DEFAULT NULL COMMENT '分析完成时间',
    `heartbeat_time`           DATETIME DEFAULT NULL COMMENT '分析心跳时间',
    `error_message`            VARCHAR(2000) DEFAULT NULL COMMENT '最后一次失败原因',
    `create_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_analysis_task_no` (`task_no`),
    UNIQUE KEY `uk_file_fingerprint_version` (`file_record_id`, `fingerprint_version`),
    KEY `idx_analysis_claim` (`status`, `log_date`, `id`),
    KEY `idx_analysis_heartbeat` (`status`, `heartbeat_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志文件分析任务及执行汇总';


CREATE TABLE IF NOT EXISTS `tb_ai_log_issue_group` (
    `id`                       BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `environment`              VARCHAR(32) NOT NULL COMMENT '环境编码',
    `system_code`              VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`              VARCHAR(128) NOT NULL COMMENT '模块编码',
    `stable_fingerprint`       CHAR(64) NOT NULL COMMENT '稳定指纹SHA-256',
    `fingerprint_version`      VARCHAR(32) NOT NULL COMMENT '指纹算法版本',
    `root_cause_category`      VARCHAR(32) NOT NULL COMMENT '根因分类',
    `ai_status`                VARCHAR(16) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/PROCESSING/COMPLETED/FAILED',
    `current_ai_item_id`       BIGINT NULL COMMENT '当前有效成功结论，重分析失败不清空',
    `active_ai_item_id`        BIGINT NULL COMMENT '已占位的当前执行Item',
    `lock_version`             INT NOT NULL DEFAULT 0 COMMENT '并发更新乐观锁；0=初始版本',
    `create_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_issue_stable` (`environment`, `system_code`, `module_code`, `stable_fingerprint`, `fingerprint_version`),
    KEY `idx_issue_ai` (`ai_status`, `active_ai_item_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志永久问题身份与当前状态';

CREATE TABLE IF NOT EXISTS `tb_ai_log_issue_group_governance` (
    `id`                       BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
    `issue_group_id`           BIGINT        NOT NULL COMMENT '永久问题 ID，与 Group 同事务创建',
    `review_status`            VARCHAR(32)   NOT NULL DEFAULT 'PENDING' COMMENT '审核状态：PENDING、APPROVED、REJECTED。',
    `reviewer_user_id`         INT           NULL COMMENT '审核用户 ID。',
    `reviewed_time`            DATETIME(3)   NULL COMMENT '最近审核时间。',
    `reviewed_ai_item_id`      BIGINT        NULL COMMENT '本次审核所依据的有效 AI Item ID。',
    `review_remark`            VARCHAR(1000) NULL COMMENT '人工审核说明。',
    `human_conclusion`         TEXT          NULL COMMENT '人工结论，不覆盖 AI 原始结果。',
    `problem_type`             VARCHAR(32)   NULL COMMENT '治理问题类型；AI 仅补齐空值，人工可修改。',
    `problem_level`            VARCHAR(32)   NULL COMMENT '治理问题等级；AI 仅补齐空值，人工可修改。',
    `resolution_days_override` INT           NULL COMMENT '人工覆盖的解决天数；为空时未设置覆盖值。',
    `owner_user_id`            INT           NULL COMMENT '被指定的责任人。',
    `assign_user_id`           INT           NULL COMMENT '最近一次指派操作人。',
    `assigned_time`            DATETIME(3)   NULL COMMENT '最近一次指派时间。',
    `claim_user_id`            INT           NULL COMMENT '实际认领人，独立于责任人。',
    `claimed_time`             DATETIME(3)   NULL COMMENT '认领时间。',
    `process_status`           VARCHAR(32)   NOT NULL DEFAULT 'PENDING' COMMENT '处理状态：PENDING、PROCESSING、RESOLVED、COMPLETED、IGNORED。',
    `resolved_user_id`         INT           NULL COMMENT '完成处理的用户 ID。',
    `resolved_time`            DATETIME(3)   NULL COMMENT '人工解决时间。',
    `resolution_remark`        VARCHAR(1000) NULL COMMENT '解决说明。',
    `completed_user_id`        INT           NULL COMMENT '验收确认人 ID。',
    `completed_time`           DATETIME(3)   NULL COMMENT '验收通过时间。',
    `completion_remark`        VARCHAR(1000) NULL COMMENT '验收说明。',
    `version`                  INT           NOT NULL DEFAULT 0 COMMENT '人工治理乐观锁版本，每次成功操作递增。',
    `create_time`              DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间。',
    `update_time`              DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近治理更新时间。',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_governance_group` (`issue_group_id`),
    KEY `idx_governance_status` (`review_status`, `process_status`, `id`),
    KEY `idx_governance_owner` (`owner_user_id`, `process_status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Group当前人工治理状态';


CREATE TABLE `tb_ai_log_error_event` (
    `id`                      BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `analysis_task_id`        BIGINT NOT NULL COMMENT '分析任务ID，不建立外键',
    `file_record_id`          BIGINT NULL COMMENT '来源文件记录ID；本地直读模式为空',
    `issue_group_id`          BIGINT DEFAULT NULL COMMENT '归属Issue聚合ID；NULL=不进入Issue治理',
    `environment`             VARCHAR(32) NOT NULL COMMENT '环境编码',
    `system_code`             VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`             VARCHAR(128) NOT NULL COMMENT '模块编码',
    `log_date`                DATE NOT NULL COMMENT '日志业务日期，来源analysis_task.log_date',
    `aggregate_type`          VARCHAR(16) NOT NULL COMMENT '聚合类型：BUSINESS=预期业务异常 ISSUE=问题治理',
    `aggregate_key`           CHAR(64) NOT NULL COMMENT '文件级聚合身份SHA-256',
    `occurrence_count`        BIGINT NOT NULL DEFAULT 1 COMMENT '当前分析任务内该聚合身份真实发生次数',
    `first_seen_time`         DATETIME(3) DEFAULT NULL COMMENT '当前分析任务内首次出现时间',
    `last_seen_time`          DATETIME(3) DEFAULT NULL COMMENT '当前分析任务内最近出现时间',
    `root_cause_category`     VARCHAR(32) NOT NULL COMMENT '分类快照：根因分类',
    `matched_rule_id`         BIGINT DEFAULT NULL COMMENT '代表样本命中的分类规则ID，内置分类时为空',
    `expected`                TINYINT(1) NOT NULL DEFAULT 0 COMMENT '分类快照：事件产生时预期事实；0=非预期 1=预期',
    `ai_required`             TINYINT(1) NOT NULL DEFAULT 1 COMMENT '分类快照：事件产生时AI路由事实；1=需要 0=不需要',
    `reason_code`             VARCHAR(128) DEFAULT NULL COMMENT '分类快照：聚合原因编码',
    `log_time`                DATETIME(3) DEFAULT NULL COMMENT '代表样本日志Header时间',
    `start_line`              BIGINT NOT NULL COMMENT '代表样本源文件起始行',
    `end_line`                BIGINT NOT NULL COMMENT '代表样本源文件结束行',
    `start_byte`              BIGINT NOT NULL COMMENT '代表样本源文件起始字节',
    `end_byte`                BIGINT NOT NULL COMMENT '代表样本源文件结束字节',
    `location_mode`           VARCHAR(32) NOT NULL COMMENT '代表样本日志定位模式',
    `truncated`               TINYINT(1) NOT NULL DEFAULT 0 COMMENT '代表样本原日志事件是否截断；0=否 1=是',
    `match_type`              VARCHAR(32) NOT NULL COMMENT '代表样本准入类型：STRICT_ERROR、FALLBACK_ERROR',
    `thread_name`             VARCHAR(512) DEFAULT NULL COMMENT '代表样本线程名',
    `trace_id`                VARCHAR(256) DEFAULT NULL COMMENT '代表样本TraceId',
    `tid`                     VARCHAR(256) DEFAULT NULL COMMENT '代表样本TID',
    `request_id`              VARCHAR(256) DEFAULT NULL COMMENT '代表样本RequestId',
    `logger_class`            VARCHAR(512) DEFAULT NULL COMMENT '代表样本Logger类名',
    `logger_method`           VARCHAR(256) DEFAULT NULL COMMENT '代表样本Logger方法名',
    `logger_line`             INT DEFAULT NULL COMMENT '代表样本Logger行号',
    `exception_class`         VARCHAR(512) DEFAULT NULL COMMENT '代表样本最外层异常类',
    `exception_message`       TEXT NULL COMMENT '代表样本最外层异常消息',
    `root_cause_exception`    VARCHAR(512) DEFAULT NULL COMMENT '代表样本根因异常类',
    `root_cause_message`      TEXT NULL COMMENT '代表样本根因异常消息',
    `business_class`          VARCHAR(512) DEFAULT NULL COMMENT '代表样本首个业务栈帧类名',
    `business_method`         VARCHAR(256) DEFAULT NULL COMMENT '代表样本首个业务栈帧方法名',
    `business_line`           INT DEFAULT NULL COMMENT '代表样本首个业务栈帧行号',
    `trigger_channel`         VARCHAR(32) NOT NULL COMMENT '代表样本触发通道',
    `normalized_message`      TEXT NULL COMMENT '代表样本脱敏归一化消息',
    `simplified_stack`        MEDIUMTEXT NULL COMMENT '代表样本限制长度后的简化调用栈',
    `strict_fingerprint`      CHAR(64) NOT NULL COMMENT '代表样本严格指纹SHA-256',
    `stable_fingerprint`      CHAR(64) NOT NULL COMMENT '稳定指纹SHA-256；Group永久身份输入，非代表样本属性',
    `fingerprint_version`     VARCHAR(32) NOT NULL COMMENT '指纹算法版本',
    `sample_content`          MEDIUMTEXT NULL COMMENT '代表样本限长原始内容',
    `sample_content_truncated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '代表样本内容是否因长度上限截断；0=否 1=是',
    `sample_quality_score`    SMALLINT NOT NULL DEFAULT 0 COMMENT '代表样本质量评分，用于跨flush替换和Group选样',
    `create_time`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_analysis_aggregate` (`analysis_task_id`, `aggregate_type`, `aggregate_key`),
    KEY `idx_event_analysis_task` (`analysis_task_id`, `id`),
    KEY `idx_event_group_date` (`issue_group_id`, `log_date`, `id`),
    KEY `idx_event_group_evidence` (`issue_group_id`, `expected`, `ai_required`, `sample_quality_score`, `id`),
    KEY `idx_event_scope_date` (`environment`, `system_code`, `module_code`, `log_date`, `expected`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志分析任务级聚合ERROR事实及代表样本';



CREATE TABLE IF NOT EXISTS `tb_ai_log_file_cleanup` (
    `id`                    BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `file_record_id`        BIGINT NOT NULL COMMENT '待清理文件记录ID',
    `analysis_task_id`      BIGINT NOT NULL COMMENT 'READY发布时创建的分析任务ID',
    `local_path`            VARCHAR(1024) NOT NULL COMMENT '待删除本地文件完整路径',
    `status`                VARCHAR(32) NOT NULL COMMENT '状态：WAITING_ANALYSIS、WAITING、DELETING、RETRY_WAITING、DELETED、MANUAL_REQUIRED',
    `trigger_reason`        VARCHAR(64) NOT NULL COMMENT '触发原因：READY_PUBLISHED、MANUAL',
    `scheduled_time`        DATETIME DEFAULT NULL COMMENT '计划清理时间',
    `deleting_time`         DATETIME DEFAULT NULL COMMENT '最近开始删除时间',
    `deleted_time`          DATETIME DEFAULT NULL COMMENT '确认删除或文件不存在时间',
    `retry_count`           INT NOT NULL DEFAULT 0 COMMENT '失败重试次数',
    `next_retry_time`       DATETIME DEFAULT NULL COMMENT '下次自动重试时间',
    `last_error_message`    VARCHAR(2000) DEFAULT NULL COMMENT '最后一次失败原因',
    `manual_required`       TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要人工处理：1是，0否',
    `remark`                VARCHAR(1000) DEFAULT NULL COMMENT '处理备注',
    `create_time`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cleanup_file` (`file_record_id`),
    KEY `idx_cleanup_schedule` (`status`, `next_retry_time`, `scheduled_time`),
    KEY `idx_cleanup_manual` (`manual_required`, `status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志本地文件清理任务及审计记录';



CREATE TABLE IF NOT EXISTS tb_ai_log_classify_rule (
    `id`              BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `analysis_module` VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '所属分析模块编码，与模块配置analysis_module一致',
    `category`        VARCHAR(32) NOT NULL COMMENT '根因分类：BUSINESS/CODE/DATABASE/EXTERNAL_SERVICE/INFRASTRUCTURE',
    `rule_type`       VARCHAR(16) NOT NULL COMMENT '规则类型：KEYWORD或REGEX',
    `match_target`    VARCHAR(16) NOT NULL DEFAULT 'ALL' COMMENT '匹配目标：EXCEPTION、MESSAGE、ALL',
    `pattern`         VARCHAR(512) NOT NULL COMMENT '匹配内容：KEYWORD为小写关键字，REGEX为正则表达式',
    `priority`        INT NOT NULL DEFAULT 100 COMMENT '优先级，小值优先，同优先级按id升序',
    `enabled`         TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    `expected`        TINYINT(1) NOT NULL DEFAULT 0 COMMENT '命中后是否为预期业务异常：1是 0否',
    `ai_required`     TINYINT(1) NOT NULL DEFAULT 1 COMMENT '命中后是否需要AI分析：1是 0否',
    `reason_code`     VARCHAR(128) NOT NULL COMMENT '分类原因和Group聚合编码',
    `remark`          VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_user_id`  INT NOT NULL DEFAULT 0 COMMENT '创建用户ID，初始化数据为0',
    `create_user_name` VARCHAR(128) NOT NULL DEFAULT 'SYSTEM' COMMENT '创建用户名',
    `create_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user_id`  INT NOT NULL DEFAULT 0 COMMENT '更新用户ID，初始化数据为0',
    `update_user_name` VARCHAR(128) NOT NULL DEFAULT 'SYSTEM' COMMENT '更新用户名',
    `update_time`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `lock_version`    INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_rule_module_type_pattern` (`analysis_module`, `rule_type`, `pattern`),
    KEY `idx_rule_module_enabled_priority` (`analysis_module`, `enabled`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志根因分类规则（按分析模块隔离，任务开始时快照加载）';

CREATE TABLE IF NOT EXISTS tb_ai_log_suppress_rule (
    `id`               BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `system_code`      VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`      VARCHAR(128) NOT NULL COMMENT '模块编码',
    `keyword`          VARCHAR(512) NOT NULL COMMENT '过滤关键词',
    `enabled`          TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
    `remark`           VARCHAR(512) DEFAULT NULL COMMENT '规则说明',
    `create_user_id`   INT NOT NULL DEFAULT 0,
    `create_user_name` VARCHAR(128) NOT NULL DEFAULT 'SYSTEM',
    `create_time`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_user_id`   INT NOT NULL DEFAULT 0,
    `update_user_name` VARCHAR(128) NOT NULL DEFAULT 'SYSTEM',
    `update_time`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `lock_version`     INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_suppress_scope_keyword` (`system_code`, `module_code`, `keyword`),
    KEY `idx_suppress_scope_enabled` (`system_code`, `module_code`, `enabled`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERROR事件前置过滤规则';



CREATE TABLE IF NOT EXISTS tb_ai_log_ai_task (
    `id`                       BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_no`                  VARCHAR(64) NOT NULL COMMENT 'AI批次号',
    `analysis_task_id`         BIGINT NOT NULL COMMENT '来源解析任务ID，不建立外键',
    `environment`              VARCHAR(32) NOT NULL COMMENT '环境编码',
    `system_code`              VARCHAR(64) NOT NULL COMMENT '系统编码',
    `module_code`              VARCHAR(64) NOT NULL COMMENT '模块编码',
    `provider_code`            VARCHAR(32) NOT NULL COMMENT '供应商编码',
    `model_code`               VARCHAR(128) NOT NULL COMMENT '请求模型编码',
    `run_no`                   INT NOT NULL DEFAULT 1 COMMENT '相同配置的执行序号',
    `selection_limit`          INT NOT NULL COMMENT '本批候选上限，最大200',
    `candidate_count`          BIGINT NOT NULL DEFAULT 0 COMMENT '符合条件的Group总数',
    `total_count`              INT NOT NULL DEFAULT 0 COMMENT '实际创建Item数',
    `status`                   VARCHAR(32) NOT NULL COMMENT 'PENDING/PREPARING/WAITING/RUNNING/SUCCESS/PARTIAL_SUCCESS/FAILED',
    `success_count`            INT NOT NULL DEFAULT 0 COMMENT '成功Item数',
    `failed_count`             INT NOT NULL DEFAULT 0 COMMENT '失败Item数',
    `total_attempt_count`      INT NOT NULL DEFAULT 0 COMMENT '真实调用总次数',
    `total_token_count`        BIGINT NOT NULL DEFAULT 0 COMMENT '全部Attempt总Token',
    `preparation_complete` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '候选是否已分批扫描完毕',
    `delivery_status`          VARCHAR(16) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/DELIVERING/SUCCESS/FAILED',
    `delivery_token`           VARCHAR(64) DEFAULT NULL COMMENT '本次OSS报告上传认领令牌',
    `delivery_attempt_count`   INT NOT NULL DEFAULT 0 COMMENT 'OSS报告上传尝试次数',
    `report_object_key`        VARCHAR(512) DEFAULT NULL COMMENT 'OSS报告对象Key',
    `delivery_error_message`   VARCHAR(512) DEFAULT NULL COMMENT '最近投递错误摘要',
    `delivery_start_time`      DATETIME DEFAULT NULL COMMENT '最近投递开始时间',
    `delivered_time`           DATETIME DEFAULT NULL COMMENT 'OSS报告上传完成时间',
    `start_time`               DATETIME DEFAULT NULL COMMENT '首次领取时间',
    `finish_time`              DATETIME DEFAULT NULL COMMENT '终态时间',
    `create_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_task_no` (`task_no`),
    UNIQUE KEY `uk_ai_task_run` (`analysis_task_id`, `provider_code`, `model_code`, `run_no`),
    KEY `idx_ai_task_analysis` (`analysis_task_id`),
    KEY `idx_ai_task_status` (`status`, `update_time`),
    KEY `idx_ai_task_delivery` (`delivery_status`, `delivery_start_time`, `id`),
    KEY `idx_ai_task_model` (`provider_code`, `model_code`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志分析批次';

CREATE TABLE IF NOT EXISTS tb_ai_log_ai_task_item (
    `id`                           BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `ai_task_id`                   BIGINT NOT NULL COMMENT 'AI批次ID，不建立外键',
    `analysis_task_id`             BIGINT NOT NULL COMMENT '来源解析任务ID，不建立外键',
    `issue_group_id`               BIGINT NOT NULL COMMENT '待分析Issue Group ID，不建立外键',
    `sample_event_id` BIGINT NOT NULL COMMENT '本次分析实际使用的代表Event',
    `selection_order`              INT NOT NULL COMMENT '候选确定性顺序',
    `occurrence_count_snapshot`    BIGINT NOT NULL COMMENT '创建时发生次数快照',
    `first_occurred_at_snapshot`   DATETIME(3) DEFAULT NULL COMMENT '创建时首次发生时间，与次数和最近时间同批统计',
    `last_occurred_at_snapshot`    DATETIME DEFAULT NULL COMMENT '创建时最近发生时间',
    `status`                       VARCHAR(32) NOT NULL COMMENT 'WAITING/RUNNING/SUCCESS/FAILED',
    `attempt_count`                INT NOT NULL DEFAULT 0 COMMENT '已开始真实调用次数',
    `max_attempts`                 INT NOT NULL DEFAULT 3 COMMENT '最大真实调用次数',
    `final_attempt_no`             INT DEFAULT NULL COMMENT '终态对应Attempt序号',
    `next_retry_time`              DATETIME DEFAULT NULL COMMENT '下次可重试时间',
    `claim_token`                  VARCHAR(64) DEFAULT NULL COMMENT '本次租约唯一令牌',
    `lease_owner`                  VARCHAR(128) DEFAULT NULL COMMENT '租约持有者',
    `lease_until`                  DATETIME DEFAULT NULL COMMENT '租约到期时间',
    `evidence_hash`                CHAR(64) DEFAULT NULL COMMENT '脱敏Evidence哈希',
    `evidence_snapshot_json`       TEXT DEFAULT NULL COMMENT '实际外发脱敏Evidence快照',
    `blame_author_name`            VARCHAR(256) DEFAULT NULL COMMENT '源码定位行最后修改Author，仅作归属线索',
    `blame_author_time`            DATETIME DEFAULT NULL COMMENT '源码定位行最后修改Author时间',
    `judgement`                    VARCHAR(32) DEFAULT NULL COMMENT 'AI判定',
    `severity`                     VARCHAR(16) DEFAULT NULL COMMENT 'AI严重程度',
    `ai_category`                  VARCHAR(32) DEFAULT NULL COMMENT 'AI分类，不覆盖确定性分类',
    `result_title`                 TEXT DEFAULT NULL COMMENT '标题，应用限制100字',
    `result_summary`               TEXT DEFAULT NULL COMMENT '摘要，应用限制300字',
    `analysis_basis`               TEXT DEFAULT NULL COMMENT '分析依据，应用限制300字',
    `root_cause`                   TEXT DEFAULT NULL COMMENT '根因结论，应用限制300字',
    `impact_description`           TEXT DEFAULT NULL COMMENT '影响，应用限制200字',
    `recommendation`               TEXT DEFAULT NULL COMMENT '唯一处理建议，应用限制300字',
    `suggested_resolution_days`    INT DEFAULT NULL COMMENT '建议解决天数，不足一天按一天计算',
    `verification`                 TEXT DEFAULT NULL COMMENT '验证方式，应用限制300字',
    `uncertainty`                  TEXT DEFAULT NULL COMMENT '不确定性，应用限制200字',
    `rule_suggestion`              TEXT DEFAULT NULL COMMENT '规则建议，应用限制300字',
    `confidence`                   DECIMAL(5,4) DEFAULT NULL COMMENT '置信度0到1',
    `human_review_required`        TINYINT(1) DEFAULT NULL COMMENT '是否需要人工复核',
    `result_hash`                  CHAR(64) DEFAULT NULL COMMENT '最终结果SHA-256',
    `input_token_count`            BIGINT NOT NULL DEFAULT 0 COMMENT 'Item累计输入Token',
    `output_token_count`           BIGINT NOT NULL DEFAULT 0 COMMENT 'Item累计输出Token',
    `total_token_count`            BIGINT NOT NULL DEFAULT 0 COMMENT 'Item累计总Token',
    `total_latency_millis`         BIGINT NOT NULL DEFAULT 0 COMMENT 'Item累计耗时',
    `last_error_code`              VARCHAR(64) DEFAULT NULL COMMENT '最近错误码',
    `last_error_message`           VARCHAR(512) DEFAULT NULL COMMENT '最近安全错误摘要',
    `rerun_operation_id`           BIGINT DEFAULT NULL COMMENT '最近一次显式重跑管理操作ID',
    `rerun_status`                 VARCHAR(16) DEFAULT NULL COMMENT '显式重跑子状态：WAITING/RUNNING/SUCCESS/FAILED',
    `rerun_execution_token`        VARCHAR(64) DEFAULT NULL COMMENT '显式重跑操作本轮执行令牌',
    `started_time`                 DATETIME DEFAULT NULL COMMENT '首次领取时间',
    `finish_time`                  DATETIME DEFAULT NULL COMMENT '终态时间',
    `create_time`                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_item_group` (`issue_group_id`, `id`),
    UNIQUE KEY `uk_ai_item_order` (`ai_task_id`, `selection_order`),
    KEY `idx_ai_item_dispatch` (`status`, `next_retry_time`, `ai_task_id`, `selection_order`),
    KEY `idx_ai_item_lease` (`status`, `lease_until`),
    KEY `idx_ai_item_rerun` (`rerun_operation_id`, `rerun_status`, `selection_order`),
    KEY `idx_ai_item_analysis` (`analysis_task_id`, `issue_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志分析Item及唯一最终结论';

CREATE TABLE IF NOT EXISTS tb_ai_log_ai_call_attempt (
    `id`                   BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `ai_task_item_id`      BIGINT NOT NULL COMMENT 'AI Item ID，不建立外键',
    `rerun_operation_id`   BIGINT DEFAULT NULL COMMENT '显式重跑管理操作ID，普通Attempt为空',
    `attempt_no`           INT NOT NULL COMMENT 'Item内真实调用序号',
    `request_id`           VARCHAR(64) NOT NULL COMMENT '应用请求ID',
    `provider_code`        VARCHAR(32) NOT NULL COMMENT '供应商编码',
    `requested_model`      VARCHAR(128) NOT NULL COMMENT '请求模型',
    `actual_model`         VARCHAR(128) DEFAULT NULL COMMENT '供应商实际返回模型',
    `provider_request_id`  TEXT DEFAULT NULL COMMENT '供应商请求或响应ID，完整保存',
    `request_mode`         VARCHAR(16) NOT NULL COMMENT 'INITIAL、RETRY或MANUAL_RERUN',
    `request_hash`         CHAR(64) NOT NULL COMMENT '请求Evidence哈希',
    `status`               VARCHAR(16) NOT NULL COMMENT 'RUNNING/SUCCESS/FAILED',
    `response_payload`     TEXT DEFAULT NULL COMMENT '供应商原始响应正文',
    `http_status`          INT DEFAULT NULL COMMENT '可获得时记录HTTP状态',
    `finish_reason`        VARCHAR(64) DEFAULT NULL COMMENT '供应商结束原因',
    `input_tokens`         BIGINT DEFAULT NULL COMMENT '输入Token',
    `output_tokens`        BIGINT DEFAULT NULL COMMENT '输出Token',
    `total_tokens`         BIGINT DEFAULT NULL COMMENT '总Token',
    `latency_millis`       BIGINT DEFAULT NULL COMMENT '本次调用耗时',
    `error_type`           VARCHAR(64) DEFAULT NULL COMMENT '错误类型',
    `error_code`           VARCHAR(64) DEFAULT NULL COMMENT '错误码',
    `error_message`        VARCHAR(512) DEFAULT NULL COMMENT '安全错误摘要',
    `retryable`            TINYINT(1) DEFAULT NULL COMMENT '本次失败是否允许重试',
    `start_time`           DATETIME NOT NULL COMMENT '真实调用开始时间',
    `finish_time`          DATETIME DEFAULT NULL COMMENT '真实调用结束时间',
    `create_time`          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_attempt_no` (`ai_task_item_id`, `attempt_no`),
    UNIQUE KEY `uk_ai_attempt_request` (`request_id`),
    KEY `idx_ai_attempt_item_time` (`ai_task_item_id`, `start_time`),
    KEY `idx_ai_attempt_rerun` (`rerun_operation_id`, `status`, `id`),
    KEY `idx_ai_attempt_provider_request` (`provider_code`, `provider_request_id`(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志真实接口调用Attempt审计';



CREATE TABLE IF NOT EXISTS tb_ai_log_management_operation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端请求幂等ID',
    actor VARCHAR(128) NOT NULL COMMENT '操作人身份',
    actor_user_id INT NULL COMMENT '操作人稳定用户ID；历史记录允许为空',
    operation_type VARCHAR(32) NOT NULL COMMENT '操作类型',
    environment VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '环境编码',
    system_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '系统编码',
    module_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '模块编码',
    target_id VARCHAR(32) NULL COMMENT '操作目标ID',
    request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '请求内容SHA-256',
    expected_revision VARCHAR(64) NULL COMMENT '客户端提交的预期版本',
    result_revision VARCHAR(64) NULL COMMENT '操作完成后的版本',
    source_item_id BIGINT NULL COMMENT '来源AI Item ID',
    reason VARCHAR(1000) NOT NULL COMMENT '操作原因',
    status VARCHAR(16) NOT NULL COMMENT '操作状态：RUNNING、SUCCESS、FAILED',
    total_count INT NOT NULL DEFAULT 0 COMMENT '固定重跑范围Item总数',
    completed_count INT NOT NULL DEFAULT 0 COMMENT '本次已完成Item数',
    success_count INT NOT NULL DEFAULT 0 COMMENT '本次成功Item数',
    failed_count INT NOT NULL DEFAULT 0 COMMENT '本次失败Item数',
    execution_token VARCHAR(64) NULL COMMENT '异步执行器fencing令牌',
    lease_until DATETIME NULL COMMENT '异步执行器租约到期时间',
    result_json TEXT NULL COMMENT '操作结果JSON',
    target_snapshot_json TEXT NULL COMMENT '创建时固定的原Item ID列表JSON',
    new_ai_task_id BIGINT NULL COMMENT '历史预留新AI任务ID，本期覆盖式重跑不使用',
    new_ai_item_id BIGINT NULL COMMENT '历史预留新AI Item ID，本期覆盖式重跑不使用',
    create_time DATETIME NOT NULL COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近进度更新时间',
    finish_time DATETIME NULL COMMENT '操作终态时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_management_request (request_id),
    KEY idx_management_scope (environment, system_code, module_code, id),
    KEY idx_management_rerun (`operation_type`, `status`, `target_id`, `lease_until`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理端写操作幂等及审计记录';

CREATE TABLE IF NOT EXISTS tb_ai_log_author_alias (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id INT NOT NULL COMMENT '本地配置账号的稳定用户ID',
    real_name VARCHAR(128) NOT NULL COMMENT '真实姓名',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用本条作者映射及兜底配置',
    is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '未命中有效映射时使用的默认人，仅启用时生效',
    alias_name VARCHAR(256) NOT NULL COMMENT 'Git Author别名',
    PRIMARY KEY (id),
    UNIQUE KEY uk_author_alias_name (alias_name),
    KEY idx_author_alias_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志Git Author与真实用户映射';

CREATE TABLE IF NOT EXISTS `tb_ai_log_ai_daily_report` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `environment` VARCHAR(32) NOT NULL COMMENT '环境',
    `system_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '空字符串表示环境全部系统',
    `log_date` DATE NOT NULL COMMENT '日报日志业务日期',
    `status` VARCHAR(16) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/SENDING/SUCCESS/FAILED',
    `send_token` VARCHAR(64) DEFAULT NULL COMMENT '当前发送令牌',
    `error_message` VARCHAR(512) DEFAULT NULL COMMENT '安全失败摘要，不保存Webhook',
    `sent_time` DATETIME DEFAULT NULL COMMENT '钉钉确认成功时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_daily_report_scope` (`environment`, `system_code`, `log_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI日志日报发送记录';
